name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-checker:
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php8.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: backend/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --no-progress
        working-directory: backend

      - name: Run local-php-security-checker
        run: local-php-security-checker backend/composer.lock
        working-directory: backend

  php-code-standard:
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php8.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --no-progress
        working-directory: backend

      - name: PHP Coding Standards
        run: |
          php-cs-fixer fix src --dry-run --rules=@Symfony --verbose
          phpstan analyse src -l9
          phpdd src
          phpcpd src --exclude 'src/Controller/Admin/' --exclude 'src/Entity'
        working-directory: backend

  lint:
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php8.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --no-progress
        working-directory: backend

      - name: PHP Lint
        run: |
          bin/console lint:twig templates --env=prod
          bin/console lint:yaml config --parse-tags
          bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
        working-directory: backend
